{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chat-app.fullname" . }}-postgres
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  postgres-user: {{ .Values.postgres.auth.username | b64enc | quote }}
  postgres-password: {{ .Values.postgres.auth.password | b64enc | quote }}
{{- end }}
