apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-app.fullname" . }}-postgres
  labels:
    {{- include "chat-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "chat-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
